#!/bin/sh
# Updates weather forecast

# check for established internet connection:
ping -q -w 1 -c 1 "$(ip r | grep default | tail -1 | cut -d ' ' -f 3)" >/dev/null || exit

# if no location argument is provided, request weather for current ip location
location="$1"
[ -z "$location" ] && location=""

curl -s "wttr.in/${location}" > /tmp/weatherreport && \
        pkill -RTMIN+5 i3blocks # && notify-send " " "🌞 Weather forecast updated."
