#!/bin/sh
# Usage: battery <battery name> - eg battery BAT0

# extract xresources colors and assign to color variables:
for x in "$(xrdb -query | grep color | grep -iv URxvt | sed "s/.*\./export /g;s/:\s*/=\"/g;s/$/\"/g")"; do eval "$x"; done

case $BLOCK_BUTTON in
    1) pgrep -x dunst >/dev/null && notify-send " " "<b>Battery module:</b>\n
⚡: fully charged
🔌: charging
🔋: discharging
🛑: not charging
♻: stagnant charge
❗: battery less than 25%!
‼ :battery less than 5%!\n" ;;
esac


# acquire battery parameters and assign to variables:
capacity=$(cat /sys/class/power_supply/"$1"/capacity) || exit
status=$(cat /sys/class/power_supply/"$1"/status)
warn1=""
# warn2=""
# set minimum battery capacity levels:
min_cap=10
critical_cap=8

# allocate a color according to battery level:
if [ "$capacity" -ge 75 ]; then
	color="$color10"
elif [ "$capacity" -ge 50 ]; then
	color="$color15"
elif [ "$capacity" -ge 25 ]; then
	color="$color11"
elif [ "$capacity" -ge "$min_cap" ]; then
	color="$color9"
	warn1="❗"
else
	color="$color9"
	warn1="❗"
	#warn2="❗"
fi


# check if the adapter is connected and charging the battery and send a critical
# notification if not - notification will self cancel when battery is charging
#if [ "$capacity" -lt "$critical_cap" ] && [ "$status" != "Charging" ]; then
#    dunstify -C 001
#    ( runner "$(flash_msg critical "<b>BATTERY CRITICAL Connect charger NOW</b>")" & )
#elif [[ "$capacity" -lt "$min_cap" && "$capacity" -ge "$critical_cap" ]] && [ "$status" != 'Charging' ]; then
#    pkill -15 -f "flash_msg critical"
#    dunstify -r 001 -u critical "Power Warning!" "<b>Battery Low - connect adaptor</b>"
#else
#    pkill -15 -f "flash_msg critical"
#    dunstify -C 001
#fi


# assign color and warning as required:
# [ -z $warn ] && warn=""
[ "$status" = "Charging" ] && color="$color14"

# _DISCH="🔋  >
# _NCHG="🛑  >
# _CHRG="🔌  >
# _UNKN="♻️ >
# _FLL="⚡" >


printf "<span color='%s'>%s%s%s%s</span>\n" "$color" "$(echo "$status" | \
    sed -e "s/,//;s/Discharging/🔋 /;s/Not charging/🛑 /;s/Charging/🔌 /;s/Unknown/♻️ /;s/Full/⚡ /;s/ 0*/ /g;s/ ://g")" \
    "$warn1" "$(echo "$capacity" | sed -e 's/$/%/')" #"$warn2"


