#!/bin/sh

# dunstmerge cal_right-top gr_bg-settings


# Get the xresources colors:
# 0:darkblack, 1:darkred,  2:darkgreen, 3:darkyellow, 4:darkblue, 5:darkmagenta, 6:darkcyan, 7:darkwhite,
# 8:black,     9:red,     10:green,    11:yellow,    12:blue,    13:magenta,    14:cyan,    15:white
for x in "$(xrdb -query | grep color | grep -iv URxvt | sed "s/.*\./export /g;s/:\s*/=\"/g;s/$/\"/g")"; do eval "$x"; done


# configure dunst settings & display cal:
calandar_send(){
    notify-send " " "$(cal --color=always | sed 's/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/')"
}

# configure dunst settings & display 3 day appointments
appointments(){
    notify-send " " "Next 3 days: $(calcurse -d3)"
}

# configute dunst settings & show info/help:
cal_info(){
    dunstmerge cal_ni_ns_right-top gr_bg-settings
    notify-send " " "<b>📅 Time/date module:</b>
- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Right click opens calcurse"
}


color1="$color7"
color2="$color11"
printf "<span color='%s'>%s</span> <span color='%s'><b>%s</b></span>\n" "$color1" "$(date '+%a %d %m %Y')" "$color2" "$(date '+%H:%M:%S')"

case $BLOCK_BUTTON in
    1) pgrep -x dunst >/dev/null; dunstmerge cal_ni_ns_right-top gr_bg-settings && calandar_send && appointments ;;
	2) pgrep -x dunst >/dev/null && cal_info ;;
	3) i3-msg -q "exec --no-startup-id $TERMINAL -f mono:pixelsize=10 -e calcurse"  ;;
esac
