#!/bin/sh


## download weather report from wttr and save to files at 3 hour intervals
update_weather() {
    [[ -s /tmp/weatherreport ]] || touch --date="00:01:00" /tmp/weatherreport
    now_hour="$(date '+%-H')"
    prev_hour="$(stat -c %y /tmp/weatherreport | awk '{print $2}' | cut -d ":" -f1 | sed 's/^0//')"
    diff_hours=$(( $now_hour - $prev_hour ))

    [[ $diff_hours -lt 0 ]] && diff_hours="$(( $diff_hours + 24 ))"
    [[ $diff_hours -gt 2 ]] && getforecast "~highgate+london?1F"
    # pgrep -x dunst >/dev/null && dunstify " " \
    #   "now: $(echo "$now_hour") prev: $(echo "$prev_hour")   diff: $(echo "$diff_hours")"
}

## download additional weather format info at one hour intervals
weather_now() {
    [[ -s /tmp/additionalweather ]] || touch --date="00:01:00" /tmp/additionalweather
    [ "$(stat -c %y /tmp/additionalweather | \
        awk '{print $2}' | cut -d ":" -f1 | sed 's/^0//')" != "$(date '+%-H')" ] && \
        curl wttr.in/~Highgate+London?format="%l:+%o+%C+%o+%t+%o+%w+%o+%P+%o+%h+%o+%m" \
        > /tmp/additionalweather
}

update_weather
weather_now


# status bar 'weather block' left-click - 1)
display_additional() {
    dunstmerge cal_right-top gr_bg-settings
    dunstify " " "$(cat /tmp/additionalweather)"
}

case $BLOCK_BUTTON in
    1) pgrep -x dunst >/dev/null && display_additional;;
    # 1) pgrep -x dunst >/dev/null && notify-send " " "$(cat /tmp/additionalweather.txt)";;
    # 2) $TERMINAL -e less -Sfr /tmp/weatherreport ;;
    2) pgrep -x dunst >/dev/null && notify-send " " "middle-button";;
    3) pgrep -x dunst >/dev/null && notify-send " " "<b>🌈 Weather module:</b>

Click for wttr.in forecast.
🌧 Chance of precipitation %
⬆ Daily high
⬇ Daily low";;
esac

printf "%s" "$(sed '16q;d' /tmp/weatherreport | grep -wo "[0-9]*%" | sort -n | sed -e '$!d' | sed -e "s/^/🌧 /g" | tr -d '\n')"

sed '13q;d' /tmp/weatherreport | grep -o "m\\(-\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print "  ⬇",$1 "°","⬆",$2 "°"}'


# ❄: Daily low
# 🌞: Daily high 
# ☔: Chance of rain/snow %
# 🌧
# ⬆ U+2B06

# ⇧  - southerly ⬆️
# ⬀  - southwesterly ↗️
# ⇨  - westerly ➡️
# ⬂  - northwesterly ↘️
# ⇩  - northerly ⬇️
# ⬃  - northeasterly ↙️
# ⇦  - easterly ⬅️
# ⬁  - southeasterly ↖️

