#!/bin/sh

case $BLOCK_BUTTON in
	1) $TERMINAL -e nmtui ;;
	3) pgrep -x dunst >/dev/null && notify-send "  Internet module:" "
- Click for \`nmtui\` for wifi access\n
📶: wifi connection with quality
📡: wifi connection established
🛑  wifi connection lost
🌐: ethernet connection established
❎: ethernet connection lost
" ;;
esac

#[ "$(cat /sys/class/net/w*/operstate)" == 'up' ] && wifiicon="📡 "
#[ "$(cat /sys/class/net/w*/operstate)" == 'down' ] && wifiicon="🛑 "

[ ! -n "${wifiicon+var}" ] && wifiicon=$(grep "^\s*w" /proc/net/wireless | awk '{ print "📶", int($3 * 100 / 70) "%" }')

printf "%s\n" "$wifiicon " # "$(cat /sys/class/net/w*/operstate | sed "s/down/🛑 / ;s/up/📡 /")"
