#!/bin/sh

filter() {
	sed "/^volume:/d" | tac | sed -e "s/\\&/&amp;/g;s/\\[paused\\].*/<span color=\"gray\" font_style=\"italic\">/g;s/\\[playing\\].*/<span>/g" | tr -d '\n' | sed -e "s/$/<\\/span>/g"
	}

case $BLOCK_BUTTON in
    1) mpc status | filter && i3-msg -q "exec --no-startup-id setsid $TERMINAL -e ncmpcpp" && pkill -SIGRTMIN+11 i3blocks & ;;
    2) mpc toggle | filter ;;  # middle click, pause/unpause
    3) mpc status | filter && pgrep -x dunst >/dev/null && dunstify " " "<b>🎵 Music module:</b>
- Shows mpd song playing.
- Italic and greyed out when paused.
- Left click opens ncmpcpp.
- Middle click toggles pause.
- Scroll changes track." ;;
    4) mpc prev   | filter ;;  # scroll up, previous
    5) mpc next   | filter ;;  # scroll down, next
    *) mpc status | filter ;;
esac


# display the 'artist - track' on the status bar:
printf "%s\n" "$(filter)"
