#!/bin/bash


DUNST_DIR="$HOME/.config/dunst"

TARGET_LAYOUT=$1
TARGET_SETTINGS=$2

[[ -f $DUNST_DIR/layouts/$TARGET_LAYOUT ]] ||\
    TARGET_LAYOUT=$(awk -F':' '$1 == "# layout" { print $2; exit }'\
    "$DUNST_DIR/dunstrc")


(
    cd "$DUNST_DIR" || exit 1
    {
    echo "#"
    figlet -f 3d.flf dunstrc | awk '{print "#  " $0}'
    echo "#"
    echo "# layout:$TARGET_LAYOUT"
    echo
    cat "layouts/${TARGET_LAYOUT}" "layouts/${TARGET_SETTINGS:-default-settings}"
    } > dunstrc
)

# dunst-theme 

dunst_restart

# set: filetype=sh
