#!/bin/sh
# A general audio interface for LARBS.

[ -z "$2" ] && num="5" || num="$2"

case "$1" in
    u*) pulsemixer --change-volume +"$num" ;;
    d*) pulsemixer --change-volume -"$num" ;;
    m*) pulsemixer --toggle-mute ;;
    truemute) pulsemixer --mute ;;
    play) mpc play ;;
    stop) mpc stop ;;
    n*) mpc next ;;
    prev) mpc prev ;;
    t*) mpc toggle ;;
    p*) mpc pause ; pauseallmpv ;;
    f*) mpc seek +"$num" ;;
    b*) mpc seek -"$num" ;;
    r*) mpc seek 0% ;;
    i*) mpc ;;
    *) cat << EOF
lmc: cli music interface for mpd and pulse for those with divine intellect too
grand to remember the mpc/pamixer commands.

Allowed options:
  [u]p NUM	Increase volume (5 points default)
  [d]own NUM	Decrease volume (5 points default)
  [m]ute	Toggle mute
  truemute	Mute
  play		Play playback
  stop		Stop playback
  [n]ext	Next track
  prev		Previous track
  [t]oggle	Toggle pause playback
  [p]ause	TruePause - pauseallmpv
  [f]oward NUM	Seek foward in song (5 secs default)
  [b]ack NUM	Seek back in song (5 secs default)
  [r]estart	Restart current song
  [i]nfo	Display current song information
  all else	Print this message

All of these commands, except for \`truemute\`, \`play\`, \`stop\`, and \`prev\` can be truncated,
i.e. \`lmc r\` for \`lmc restart\`.
EOF
esac

pkill -RTMIN+10 i3blocks
