#!/bin/sh
# This script is called by i3 on startup to remap keys.

# Increase key speed via a rate change
xset r rate 300 40

# Screen Saver
xset s off

# pointer control
xset m 2/1 4

# set dmps standby suspend off
xset dpms 0 0 0
# disable DPMS (Energy Star)
xset -dpms

# Map the caps lock key to super...
# setxkbmap -option caps:super
# Map the caps lock key to control...
# setxkbmap -option caps:ctrl
setxkbmap -option ctrl:nocaps

# But when it is pressed only once, treat it as escape.
# killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'
killall xcape 2>/dev/null ; xcape -e 'Control_L=Escape'

# Map the menu button to right super as well.
xmodmap -e 'keycode 135 = Super_R'
