#!/bin/sh

# TODO - get current screen resolution and asign to varable for 'resize image':

# Sets the background. If given an argument, will set file as background.
[ ! -z "$1" ] && cp "$1" ~/.config/wall.png && notify-send -i "$HOME/.config/wall.png" "Wallpaper changed."

# also create a lo-rez blured copy to be used as a lock-screen image
convert ~/.config/wall.png -resize 5% -resize 1920x1080\! -paint 3 ~/.config/lock.png &

xwallpaper --stretch ~/.config/wall.png
