#!/bin/sh
alias ka="killall" \
    sudo="sudo " \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	magit="nvim -c Magit" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="vifm" \
	r="ranger" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
    nv="nvim" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -NF --color=auto --group-directories-first" \
	la="ls -A" \
	ll="ls -lA" \
	lf="ls -l" \
	ld="ls -dl" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
    ccat="highlight -O truecolor" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	tree="tree -A" \
    tn="tmux new-session -s" \
    ta="tmux attach -t" \
    tl="tmux ls" \
    tk="tmux kill-session -t" \
    rm="rm -iv"

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.
