#!/bin/bash
stty -ixon # Disable ctrl-s and ctrl-q.
shopt -s autocd #Allows you to cd into directory merely by typing the directory name.

# Disable CTRL-D, avoid accidently terminating shell
set -o ignoreeof

HISTCONTROL="erasedups:ignoreboth"
HISTIGNORE="clear:exit:cd:pwd:ls:la:ll:lx:lf:ld:ls -l:history"
HISTSIZE=HISTFILESIZE= # Infinite history.

export PS1="\[$(tput bold)\]\[$(tput setaf 1)\][\[$(tput setaf 3)\]\u\[$(tput setaf 2)\]@\[$(tput setaf 4)\]\h \[$(tput setaf 6)\]\W\[$(tput setaf 1)\]]\[$(tput setaf 7)\]\\$ \[$(tput sgr0)\]"


[ -f "$HOME/.shortcutrc" ] && source "$HOME/.shortcutrc" # Load shortcut aliases
[ -f "$HOME/.config/dotfiles/bash/aliasrc" ] && source "$HOME/.config/dotfiles/bash/aliasrc"
[ -f "$HOME/.config/dotfiles/bash/functions" ] && source "$HOME/.config/dotfiles/bash/functions"
# [ -f "$HOME/.bash_prompt" ] && source "$HOME/.bash_prompt" # Load bash_prompt - contains git prompt

# git repo prompt - bash-git-prompt.git
if [ -f "$HOME/.config/bash-git-prompt/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=0
    GIT_PROMPT_THEME=Custom
    source "$HOME"/.config/bash-git-prompt/gitprompt.sh
fi

# Make pypi2pkgbuild easier - creating/installing PKGBUILD
alias pypi2pkgalias='PKGEXT=.pkg.tar pypi2pkgbuild.py -g cython -b
/tmp/pypi2pkgbuild/ -f'

# virtual environment management - python:
# set up directory location for venv directories:
export VENV_DIR="$HOME/bin/virtualenvs/"
export SYSTEMD_EDITOR=nvim

# create virtualenv dir if it does not exist:
if [[ ! -d $VENV_DIR ]]; then
    mkdir $VENV_DIR
fi

# shell completion of pipenv:
# eval "$(pipenv --completion)"


[ -f ~/.fzf.bash ] && source ~/.fzf.bash
